name: Build MCP Email Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g pkg

    - name: Build TypeScript
      run: npm run build

    - name: Package executable
      run: npm run pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: email-mcp-executables
        path: dist/
        retention-days: 3
